export const ADMIN_ONBOARDING_PAGE_STEP_DEFINITIONS = [
  {
    target: 'page-dashboard-stats',
    routePath: '/admin',
    title: 'Dashboard metrics',
    description:
      'Live counts for leads, bookings, sessions, users, and templates. Each card links to the related workspace.',
    side: 'bottom',
  },
  {
    target: 'page-dashboard-activity',
    routePath: '/admin',
    title: 'Recent activity',
    description:
      'This week’s bookings (Manila Sun–Sat) plus recent leads and sessions so you can spot what needs follow-up.',
    side: 'top',
  },
  {
    target: 'page-templates-list',
    routePath: '/admin/diagnostic-templates',
    title: 'Template library',
    description: 'Search templates, create new ones, and open a template to edit rounds, questions, and activation.',
    side: 'top',
  },
  {
    target: 'page-blog-list',
    routePath: '/admin/blog-posts',
    title: 'Blog posts',
    description: 'Draft and publish MDX articles for the marketing site. Use New post to open the editor.',
    side: 'top',
  },
  {
    target: 'page-sessions-table',
    routePath: '/admin/sessions',
    title: 'Diagnostic sessions',
    description:
      'Every guided diagnostic run with completion state, payment status, and links to bookings when a slot was reserved.',
    side: 'top',
  },
  {
    target: 'page-leads-table',
    routePath: '/admin/leads',
    title: 'Leads table',
    description: 'Contacts from web and native journeys—sort, search, and open records for follow-up.',
    side: 'top',
  },
  {
    target: 'page-users-table',
    routePath: '/admin/users',
    title: 'Marketing users',
    description: 'Registered accounts with auth sessions. Open a user for quiz snapshots and sign-in history.',
    side: 'top',
  },
  {
    target: 'page-schedule-tabs',
    routePath: '/admin/schedule',
    routeHref: '/admin/schedule',
    title: 'Schedule sections',
    description:
      'Five tabs configure baseline hours, weekday rules, one-off dates, optional caps, and a week preview before publishing.',
    side: 'bottom',
  },
  {
    target: 'page-schedule-hours-grid',
    routePath: '/admin/schedule',
    routeHref: '/admin/schedule',
    title: 'Hours & grid',
    description:
      'Booking horizon, default weekday hours, slot interval, and weekend days—all in Asia/Manila time.',
    side: 'top',
  },
  {
    target: 'page-schedule-weekdays',
    routePath: '/admin/schedule',
    routeHref: '/admin/schedule?tab=weekdays',
    title: 'Weekday rules',
    description: 'Per-day overrides: follow defaults, close entirely, or set custom hours (e.g. shorter Friday).',
    side: 'top',
  },
  {
    target: 'page-schedule-dates',
    routePath: '/admin/schedule',
    routeHref: '/admin/schedule?tab=dates',
    title: 'Date overrides',
    description: 'Highest priority: holidays, travel, or a single open Saturday—replaces weekday rules for that date only.',
    side: 'top',
  },
  {
    target: 'page-schedule-caps',
    routePath: '/admin/schedule',
    routeHref: '/admin/schedule?tab=caps',
    title: 'Booking caps',
    description: 'Optional soft limits per calendar day or ISO week on active bookings. Leave empty for unlimited capacity.',
    side: 'top',
  },
  {
    target: 'page-schedule-preview',
    routePath: '/admin/schedule',
    routeHref: '/admin/schedule?tab=preview',
    title: 'Week preview',
    description: 'Template week grid—gray cells are closed. Customer apps use the live availability API after you save.',
    side: 'top',
  },
  {
    target: 'page-bookings-view-toggle',
    routePath: '/admin/bookings',
    routeHref: '/admin/bookings',
    title: 'Table or calendar',
    description: 'Switch between Table and Calendar—both share the same filters, date range, and reference search.',
    side: 'left',
  },
  {
    target: 'page-bookings-filters',
    routePath: '/admin/bookings',
    routeHref: '/admin/bookings',
    title: 'Booking filters',
    description:
      'Filter bookings by status in either view—confirmed, awaiting payment, pending hold, completed, or cancelled.',
    side: 'right',
  },
  {
    target: 'page-bookings-table',
    routePath: '/admin/bookings',
    routeHref: '/admin/bookings',
    title: 'Bookings table',
    description:
      'Sortable rows with start time, reference, contact, status, and session links. Paginate and open a row for full booking detail.',
    side: 'top',
  },
  {
    target: 'page-bookings-calendar',
    routePath: '/admin/bookings',
    routeHref: '/admin/bookings?view=calendar',
    title: 'Bookings calendar',
    description:
      'Month, week, day, or list in Manila time. Click an event for payment gateway, hold expiry, Meet link, and diagnostic context.',
    side: 'top',
  },
  {
    target: 'page-support-reports-table',
    routePath: '/admin/support-reports',
    title: 'Support reports',
    description:
      'User-submitted issues from the marketing site and native app—with route, screenshots, and admin reply threads.',
    side: 'top',
  },
  {
    target: 'page-debug-tabs',
    routePath: '/admin/debug',
    routeHref: '/admin/debug',
    title: 'Debug sections',
    description:
      'Three tabs—Client diagnostic, Cron logs, and Payment logs—for checkout, scheduler, and gateway troubleshooting.',
    side: 'bottom',
  },
  {
    target: 'page-debug-client-diagnostic',
    routePath: '/admin/debug',
    routeHref: '/admin/debug',
    title: 'Client diagnostic',
    description:
      'Look up a marketing session ref (24-char hex or qs1.* token) and/or booking reference to see payability, holds, and booking linkage.',
    side: 'top',
  },
  {
    target: 'page-debug-cron-logs',
    routePath: '/admin/debug',
    routeHref: '/admin/debug?tab=cron-logs',
    title: 'Cron logs',
    description:
      'Every POST to /api/cron/*—job name, trigger, duration, result counts, errors, and unauthorized attempts.',
    side: 'top',
  },
  {
    target: 'page-debug-payment-logs',
    routePath: '/admin/debug',
    routeHref: '/admin/debug?tab=payment-logs',
    title: 'Payment logs',
    description:
      'Webhook POSTs to /api/webhooks/* with gateway, parsed status, matched transaction/booking, HTTP response, and payload snippets.',
    side: 'top',
  },
  {
    target: 'page-advisor-chat',
    routePath: '/admin/advisor',
    title: 'Strategic advisor',
    description: 'Internal AI chat for product and business decisions. Use Cmd/Ctrl+Enter to send a message.',
    side: 'top',
  },
  {
    target: 'page-settings-tabs',
    routePath: '/admin/settings',
    routeHref: '/admin/settings',
    title: 'Settings sections',
    description:
      'Eight tabs—General, SEO, Pricing, Payments, Email, Support, Meetings, and Recordings. Save or reset the active tab with the sticky footer.',
    side: 'bottom',
  },
  {
    target: 'page-settings-general',
    routePath: '/admin/settings',
    routeHref: '/admin/settings',
    title: 'General',
    description: 'Diagnostic intake, branding, and core site configuration for web and native experiences.',
    side: 'top',
  },
  {
    target: 'page-settings-seo',
    routePath: '/admin/settings',
    routeHref: '/admin/settings?tab=seo',
    title: 'SEO',
    description:
      'Site-wide meta defaults, search console verification, social cards, and per-page title/description overrides for marketing routes.',
    side: 'top',
  },
  {
    target: 'page-settings-pricing',
    routePath: '/admin/settings',
    routeHref: '/admin/settings?tab=pricing',
    title: 'Pricing',
    description: 'Consultation pricing, packages, and amounts shown during checkout and on the marketing site.',
    side: 'top',
  },
  {
    target: 'page-settings-payments',
    routePath: '/admin/settings',
    routeHref: '/admin/settings?tab=payments',
    title: 'Payments',
    description: 'Enable gateways (PayMongo, Xendit, HitPay, PayPal), reserve-then-pay holds, sandbox mode, and credentials.',
    side: 'top',
  },
  {
    target: 'page-settings-email',
    routePath: '/admin/settings',
    routeHref: '/admin/settings?tab=email',
    title: 'Email',
    description: 'Transactional email provider, sender identity, and templates for booking and payment notifications.',
    side: 'top',
  },
  {
    target: 'page-settings-support',
    routePath: '/admin/settings',
    routeHref: '/admin/settings?tab=support',
    title: 'Support',
    description: 'In-app support inbox settings—where user reports from web and native are delivered and replied to.',
    side: 'top',
  },
  {
    target: 'page-settings-meetings',
    routePath: '/admin/settings',
    routeHref: '/admin/settings?tab=meetings',
    title: 'Meetings',
    description: 'Google Meet and calendar integration for confirmed bookings—links and conferencing defaults.',
    side: 'top',
  },
  {
    target: 'page-settings-recordings',
    routePath: '/admin/settings',
    routeHref: '/admin/settings?tab=recordings',
    title: 'Recordings',
    description: 'Fathom webhook configuration to attach meeting notes and recordings to bookings after sessions.',
    side: 'top',
  },
] as const;
