export const ADMIN_ONBOARDING_PAGE_STEP_DEFINITIONS = [
  {
    target: 'page-dashboard-stats',
    routePath: '/admin',
    title: 'Dashboard metrics',
    description: 'Live counts for leads, bookings, sessions, users, and templates. Each card links to the related workspace.',
    side: 'bottom',
  },
  {
    target: 'page-dashboard-activity',
    routePath: '/admin',
    title: 'Recent activity',
    description: 'This week’s bookings plus recent leads and sessions so you can spot what needs follow-up.',
    side: 'top',
  },
  {
    target: 'page-templates-list',
    routePath: '/admin/diagnostic-templates',
    title: 'Template library',
    description: 'Search templates, create new ones, and open a template to edit rounds, questions, and activation.',
    side: 'top',
  },
  {
    target: 'page-blog-list',
    routePath: '/admin/blog-posts',
    title: 'Blog posts',
    description: 'Draft and publish MDX articles for the marketing site. Use New post to open the editor.',
    side: 'top',
  },
  {
    target: 'page-sessions-table',
    routePath: '/admin/sessions',
    title: 'Diagnostic sessions',
    description: 'Every guided diagnostic run with completion state and links to bookings when a slot was reserved.',
    side: 'top',
  },
  {
    target: 'page-leads-table',
    routePath: '/admin/leads',
    title: 'Leads table',
    description: 'Contacts from web and native journeys—sort, search, and open records for follow-up.',
    side: 'top',
  },
  {
    target: 'page-users-table',
    routePath: '/admin/users',
    title: 'Marketing users',
    description: 'Registered accounts with auth sessions. Open a user for quiz snapshots and sign-in history.',
    side: 'top',
  },
  {
    target: 'page-schedule-calendar',
    routePath: '/admin/schedule',
    title: 'Advisor schedule',
    description: 'Set availability windows, caps, and rules that generate bookable slots on the marketing site.',
    side: 'top',
  },
  {
    target: 'page-bookings-filters',
    routePath: '/admin/bookings',
    title: 'Booking filters',
    description: 'Filter the calendar by status—confirmed, pending, or cancelled—like folders in an inbox.',
    side: 'right',
  },
  {
    target: 'page-bookings-calendar',
    routePath: '/admin/bookings',
    title: 'Bookings calendar',
    description: 'Month, week, day, or list views in Manila time. Click an event for payment and diagnostic details.',
    side: 'top',
  },
  {
    target: 'page-advisor-chat',
    routePath: '/admin/advisor',
    title: 'Strategic advisor',
    description: 'Internal AI chat for product and business decisions. Use Cmd/Ctrl+Enter to send a message.',
    side: 'top',
  },
  {
    target: 'page-settings-tabs',
    routePath: '/admin/settings',
    title: 'Settings sections',
    description: 'Switch between General, Pricing, Payments, Email, and Meetings configuration tabs.',
    side: 'bottom',
  },
  {
    target: 'page-settings-content',
    routePath: '/admin/settings',
    title: 'Settings forms',
    description: 'Edit the active tab, then save or reset with the sticky footer. Unsaved changes stay on this tab.',
    side: 'top',
  },
] as const;
