/** Auto-generated by scripts/generate-techmd-brand-assets.py — do not edit manually. */
export const BRAND_ASSET_VERSION = 'e6df2a08061f' as const;

export const BRAND_LOGO_FULL_LIGHT = 'techmd-logo-full.png' as const;
export const BRAND_LOGO_COMPACT_LIGHT = 'techmd-logo-compact.png' as const;
export const BRAND_LOGO_FULL_DARK = 'techmd-logo-full-dark.png' as const;
export const BRAND_LOGO_COMPACT_DARK = 'techmd-logo-compact-dark.png' as const;
export const BRAND_MARK_LIGHT = 'techmd-mark.png' as const;
export const BRAND_MARK_DARK = 'techmd-mark-dark.png' as const;

/** Public URL for a brand raster under `/brand/`, with a cache-busting query param. */
export function brandAssetUrl(fileName: string): string {
  const normalized = fileName.startsWith('/brand/') ? fileName.slice('/brand/'.length) : fileName;
  return `/brand/${normalized}?v=${BRAND_ASSET_VERSION}`;
}
