export const DEFAULT_REPORTER_REPLY_MIN_INTERVAL_SECONDS = 120;
export const DEFAULT_REPORTER_REPLY_MAX_PER_HOUR = 6;
export const MIN_REPORTER_REPLY_INTERVAL_SECONDS = 30;
export const MAX_REPORTER_REPLY_INTERVAL_SECONDS = 3600;
export const MIN_REPORTER_REPLY_MAX_PER_HOUR = 1;
export const MAX_REPORTER_REPLY_MAX_PER_HOUR = 30;
